# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
  push:
    branches:
    - "main"
    paths:
    - ".github/workflows/**"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: H4M5TER
          template: classic
          base: header, activity, community, repositories, metadata
          commits_authoring: H4M5TER, 仓鼠, zhuxx2003@163.com, zhuxx2003@gmail.com
          config_timezone: Asia/Hong_Kong
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_lines: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: H4M5TER
          repositories_affiliations: owner, collaborator
